mysql:
  host: "localhost"
  port: 3306
  username: 'root'
  password: "root"
  database: "rpgproject"

potions:
  health:
    type: health
    material: "POTION"
    custom-model-data: 2
    tier-1-buff: 50 # this is the total amount healed
    tier-2-buff: 100
    tier-3-buff: 150
  overtime-health:
    type: progressive-health
    material: "POTION" # the plugin looks for items with this material
    custom-model-data: 1 # and this custom model data
    tier-1:
      duration: 10 # this is the duration in seconds of the buff
      buff: 50 # this is the total amount healed
    tier-2:
      duration: 20
      buff: 100
    tier-3:
      duration: 30
      buff: 150

armor:
  iron-helmet:
    health-buff: 10
    regeneration-buff: 0.05
    material: "IRON_HELMET" # the plugin looks for items with this material
    custom-model-data: 1 # and this custom model data
  iron-chestplate:
    health-buff: 13
    regeneration-buff: 0.05
    material: "IRON_CHESTPLATE"
    custom-model-data: 2
  iron-leggings:
    health-buff: 12
    regeneration-buff: 0.05
    material: "IRON_LEGGINGS"
    custom-model-data: 3
  iron-boots:
    health-buff: 11
    regeneration-buff: 0.05
    material: "IRON_BOOTS"
    custom-model-data: 4

static-items:
  resource-bag-14:
    name: "Resource Bag"
    lore: "A bag full of resources. Size 14"
    material: "CHEST"
    custom-model-data: 1
  resource-bag-21:
    name: "Resource Bag"
    lore: "A bag full of resources. Size 21"
    material: "CHEST"
    custom-model-data: 2
  resource-bag-28:
    name: "Resource Bag"
    lore: "A bag full of resources. Size 28"
    material: "CHEST"
    custom-model-data: 3

resource-bag-pickup-items:
  - "IRON_INGOT:1"

classes:
  archer:
    name: "Archer"
    description: "Increase your archery skills."