potions:
  overtime-health:
    name: "Progressive Health Potion"
    description: "Slowly regenerates health."
    type: progressive-health
classes:
  archer:
    name: "Archer"
    description: "Increase your archery skills."