mysql:
  host: "localhost"
  port: 3306
  username: 'root'
  password: "root"
  database: "rpgproject"

progressive-potion-bundle-item:
  material: "POTION"
  custom-model-data: 1
  title: "Progressive Potion Bundle"
  lore:
      - "A bundle of potions."
      - "Right click to open."
      - "Contains %potion-count% potions."
      - "1. %potion-1% +%potion-1-buff% (%potion-1-duration%s)" # %potion-1% will be replaced with the name of the potion in the first slot, if it doesn't exist, the line will be removed.
      - "2. %potion-2% +%potion-2-buff% (%potion-2-duration%s)"
      - "3. %potion-3% +%potion-2-buff% (%potion-3-duration%s)"

potions:
  health:
    type: health
    material: "POTION"
    custom-model-data: 2
    formatted-name: "Health"
    title: "Health Potion %tier%" # %tier% will be replaced with the tier of the potion
    lore:
      - "Heals you for %buff% health." # %buff% will be replaced with the buff of the potion
      - "Has %uses% left." # %uses% will be replaced with the uses of the potion
    bundle-material: "POTION"
    bundle-custom-model-data: 2
    bundle-title: "Health Potion Bundle"
    bundle-lore:
      - "A bundle of health potions."
      - "Right click to open."
      - "Contains %potion-count% health potions."
      - "1. %potion-1% +%potion-1-buff% [%potion-1-uses%]" # %potion-1% will be replaced with the name of the potion in the first slot, if it doesn't exist, it will show N/A.
      - "2. %potion-2% +%potion-2-buff% [%potion-2-uses%]" # %potion-2-buff% will be replaced with the buff of the potion in the second slot, if it doesn't exist, it will show N/A.
      - "3. %potion-3% +%potion-3-buff% [%potion-3-uses%]" 
    tier-1:
      min-buff: 6
      max-buff: 14
      min-uses: 7
      max-uses: 15
    tier-2:
      min-buff: 20
      max-buff: 55
      min-uses: 3
      max-uses: 10
    tier-3:
      min-buff: 80
      max-buff: 150
      min-uses: 3
      max-uses: 10
  progressive-health:
    type: progressive-health
    material: "POTION" # the plugin looks for items with this material
    custom-model-data: 1 # and this custom model data
    formatted-name: "Progressive Health"
    title: "Progressive Health Potion %tier%" # %tier% will be replaced with the tier of the potion
    lore:
      - "Heals you for %buff% health over %duration%s." # %buff% will be replaced with the buff of the potion, %duration% will be replaced with the duration of the potion
      - "Has %uses% left." # %uses% will be replaced with the uses of the potion

    bundle-material: "POTION"
    bundle-custom-model-data: 1
    bundle-title: "Progressive Health Potion Bundle"
    bundle-lore:
      - "A bundle of potions."
      - "Right click to open."
      - "Contains %potion-count% potions."
      - "1. %potion1% - %potion1-buff% (%potion1-duration%s)" # %potion-1% will be replaced with the name of the potion in the first slot, if it doesn't exist, the line will be removed.
      - "2. %potion2% - %potion2-buff% (%potion2-duration%s)"
      - "3. %potion3% - %potion3-buff% (%potion3-duration%s)"

    tier-1:
      min-duration: 3 # this is the duration in seconds of the buff
      max-duration: 3
      min-buff: 6
      max-buff: 14
      min-uses: 3
      max-uses: 10
    tier-2:
      min-duration: 2
      max-duration: 3
      min-buff: 20
      max-buff: 55
      min-uses: 3
      max-uses: 10
    tier-3:
      min-duration: 1
      max-duration: 2
      min-buff: 80
      max-buff: 150
      min-uses: 3
      max-uses: 10

armor:
  iron-helmet:
    health-buff: 10
    regeneration-buff: 0.05
    material: "IRON_HELMET" # the plugin looks for items with this material
    custom-model-data: 1 # and this custom model data
  iron-chestplate:
    health-buff: 13
    regeneration-buff: 0.05
    material: "IRON_CHESTPLATE"
    custom-model-data: 2
  iron-leggings:
    health-buff: 12
    regeneration-buff: 0.05
    material: "IRON_LEGGINGS"
    custom-model-data: 3
  iron-boots:
    health-buff: 11
    regeneration-buff: 0.05
    material: "IRON_BOOTS"
    custom-model-data: 4

static-items:
  resource-bag-14:
    name: "Resource Bag"
    lore: "A bag full of resources. Size 14"
    material: "CHEST"
    custom-model-data: 1
  resource-bag-21:
    name: "Resource Bag"
    lore: "A bag full of resources. Size 21"
    material: "CHEST"
    custom-model-data: 2
  resource-bag-28:
    name: "Resource Bag"
    lore: "A bag full of resources. Size 28"
    material: "CHEST"
    custom-model-data: 3

resource-bag-pickup-items:
  - "IRON_INGOT:1"

classes:
  archer:
    name: "Archer"
    description: "Increase your archery skills."