mysql:
  host: "localhost"
  port: 3306
  username: 'root'
  password: "root"
  database: "rpgproject"

potions:
  health:
    type: health
    material: "POTION"
    custom-model-data: 2
    tier-1:
      min-buff: 6
      max-buff: 14
      min-uses: 7
      max-uses: 15
    tier-2:
      min-buff: 20
      max-buff: 55
      min-uses: 3
      max-uses: 10
    tier-3:
      min-buff: 80
      max-buff: 150
      min-uses: 3
      max-uses: 10
  overtime-health:
    type: progressive-health
    material: "POTION" # the plugin looks for items with this material
    custom-model-data: 1 # and this custom model data
    tier-1:
      min-duration: 3 # this is the duration in seconds of the buff
      max-duration: 3
      min-buff: 6
      max-buff: 14
      min-uses: 3
      max-uses: 10
    tier-2:
      min-duration: 2
      max-duration: 3
      min-buff: 20
      max-buff: 55
      min-uses: 3
      max-uses: 10
    tier-3:
      min-duration: 1
      max-duration: 2
      min-buff: 80
      max-buff: 150
      min-uses: 3
      max-uses: 10

armor:
  iron-helmet:
    health-buff: 10
    regeneration-buff: 0.05
    material: "IRON_HELMET" # the plugin looks for items with this material
    custom-model-data: 1 # and this custom model data
  iron-chestplate:
    health-buff: 13
    regeneration-buff: 0.05
    material: "IRON_CHESTPLATE"
    custom-model-data: 2
  iron-leggings:
    health-buff: 12
    regeneration-buff: 0.05
    material: "IRON_LEGGINGS"
    custom-model-data: 3
  iron-boots:
    health-buff: 11
    regeneration-buff: 0.05
    material: "IRON_BOOTS"
    custom-model-data: 4

static-items:
  resource-bag-14:
    name: "Resource Bag"
    lore: "A bag full of resources. Size 14"
    material: "CHEST"
    custom-model-data: 1
  resource-bag-21:
    name: "Resource Bag"
    lore: "A bag full of resources. Size 21"
    material: "CHEST"
    custom-model-data: 2
  resource-bag-28:
    name: "Resource Bag"
    lore: "A bag full of resources. Size 28"
    material: "CHEST"
    custom-model-data: 3

resource-bag-pickup-items:
  - "IRON_INGOT:1"

classes:
  archer:
    name: "Archer"
    description: "Increase your archery skills."